### ISSUE TITLE
ClassNotFoundException: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException

### ISSUE THREAD

**Issue by ropoman** [infonl/solr-app-magnolia-module#1]
Hi, I'm using 5.4.2 and get the following exception. Afterwards I see no app.

    <dependency>
      <groupId>info.magnolia.solr</groupId>
      <artifactId>magnolia-content-indexer</artifactId>
      <version>5.0</version>
    </dependency><dependency>
      <groupId>info.magnolia.solr</groupId>
      <artifactId>magnolia-solr-search-provider</artifactId>
      <version>5.0</version>
    </dependency>
    <dependency>
    	<groupId>nl.info.magnolia</groupId>                  
    	<artifactId>solr-app-magnolia-module</artifactId>
    	<version>1.0.2</version>
    </dependency>

		
		2015-10-15 12:20:34,959 AUTHOR WARN  .magnolia.config.source.jcr.JcrConfigurationSource: Problem while registering APP from /modules/solr-app/apps/solr: No class def found error: org/apache/solr/client/solrj/impl/HttpSolrServer$RemoteSolrException
java.lang.NoClassDefFoundError: org/apache/solr/client/solrj/impl/HttpSolrServer$RemoteSolrException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at info.magnolia.objectfactory.DefaultClassFactory.forName(DefaultClassFactory.java:50)
	at info.magnolia.module.groovy.support.classes.GroovyClassFactory.forName(GroovyClassFactory.java:86)
	at info.magnolia.jcr.node2bean.impl.Node2BeanTransformerImpl.convertPropertyValue(Node2BeanTransformerImpl.java:279)
	at info.magnolia.jcr.node2bean.impl.Node2BeanTransformerImpl.setProperty(Node2BeanTransformerImpl.java:401)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.setProperties(Node2BeanProcessorImpl.java:266)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toBean(Node2BeanProcessorImpl.java:147)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toMap(Node2BeanProcessorImpl.java:227)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toBean(Node2BeanProcessorImpl.java:132)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toMap(Node2BeanProcessorImpl.java:227)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toBean(Node2BeanProcessorImpl.java:132)
	at info.magnolia.jcr.node2bean.impl.Node2BeanProcessorImpl.toBean(Node2BeanProcessorImpl.java:107)
	at info.magnolia.config.source.jcr.JcrConfigurationSource.newProvider(JcrConfigurationSource.java:165)
	at info.magnolia.config.source.jcr.JcrConfigurationSource$1.visit(JcrConfigurationSource.java:137)
	at info.magnolia.jcr.util.NodeUtil.visit(NodeUtil.java:651)
	at info.magnolia.config.source.jcr.JcrConfigurationSource.collectProvidersFor(JcrConfigurationSource.java:132)
	at info.magnolia.config.source.jcr.JcrConfigurationSource.reload(JcrConfigurationSource.java:125)
	at info.magnolia.config.source.jcr.RegistryBasedObservingManager.reload(RegistryBasedObservingManager.java:60)
	at info.magnolia.cms.util.ModuleConfigurationObservingManager.reload(ModuleConfigurationObservingManager.java:98)
	at info.magnolia.cms.util.WorkspaceObservingManager.start(WorkspaceObservingManager.java:104)
	at info.magnolia.config.source.jcr.JcrConfigurationSource.start(JcrConfigurationSource.java:118)
	at info.magnolia.config.source.jcr.JcrConfigurationSourceBuilder.bindTo(JcrConfigurationSourceBuilder.java:85)
	at info.magnolia.config.source.jcr.JcrConfigurationSourceBuilder.bindWithDefaults(JcrConfigurationSourceBuilder.java:92)
	at info.magnolia.ui.framework.UiFrameworkModule.start(UiFrameworkModule.java:75)
	at info.magnolia.module.ModuleManagerImpl.startModule(ModuleManagerImpl.java:402)
	at info.magnolia.module.ModuleManagerImpl.startModules(ModuleManagerImpl.java:343)
	at info.magnolia.module.ui.ModuleManagerWebUI$1.doExec(ModuleManagerWebUI.java:104)
	at info.magnolia.context.MgnlContext$VoidOp.exec(MgnlContext.java:421)
	at info.magnolia.context.MgnlContext$VoidOp.exec(MgnlContext.java:418)
	at info.magnolia.context.MgnlContext.doInSystemContext(MgnlContext.java:392)
	at info.magnolia.module.ui.ModuleManagerWebUI.execute(ModuleManagerWebUI.java:100)
	at info.magnolia.module.ui.InstallationFilter.doFilter(InstallationFilter.java:100)
	at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85)
	at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:79)
	at info.magnolia.cms.filters.MgnlFilterChain.doFilter(MgnlFilterChain.java:81)
	at info.magnolia.cms.filters.CompositeFilter.doFilter(CompositeFilter.java:65)
	at info.magnolia.cms.filters.AbstractMgnlFilter.doFilter(AbstractMgnlFilter.java:85)
	at info.magnolia.cms.filters.SafeDestroyMgnlFilterWrapper.doFilter(SafeDestroyMgnlFilterWrapper.java:107)
	at info.magnolia.cms.filters.MgnlFilterDispatcher.doDispatch(MgnlFilterDispatcher.java:67)
	at info.magnolia.cms.filters.MgnlMainFilter.doFilter(MgnlMainFilter.java:108)
	at info.magnolia.cms.filters.MgnlMainFilter.doFilter(MgnlMainFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1015)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1284)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1132)
	... 60 more

**Comment by edgarvonk** [comment]
Hi ropoman, 

Thanks for reporting this.

Had a quick look at it and it appears that the Solr App Module is not compatible with the new version 5.0 of Magnolia's Solr Search Modules. It does work with version 3.0 of these modules. I will fix this a.s.a.p.

cheers

**Comment by edgarvonk** [comment]
I have created [a branch](https://github.com/infonl/solr-app-magnolia-module/tree/feature/solr-5-support) to work on upgrading to version 5.0 of the Magnolia Solr Modules. Note that you need to upgrade to Solr 5 as well since version 5.0 of the Magnolia Solr Modules are not backwards compatible with Solr 4 (I tried). I have not been able to test it yet and so have not created a release yet.

**Comment by edgarvonk** [comment]
I also deployed a [2.0.0-SNAPSHOT version of my module to Magnolia's Nexus](https://nexus.magnolia-cms.com/content/repositories/magnolia.forge.snapshots/nl/info/magnolia/solr-app-magnolia-module/2.0.0-SNAPSHOT/). I think it should work on Solr 5 but have not been able to test this yet.

**Comment by ropoman** [comment]
Thanks. It is great to come back from the weekend and find your problems solved ;)

This command is called cleanSolr, not clearSolr. And it does not delete all files, only the ones with status code 404:
2015-10-19 08:30:46,048 AUTHOR ERROR nl.info.magnolia.solr.app.SolrManagementSubApp    : Failed to execute 'clearSolr' command in catalog 'solr'
java.lang.Exception: Command [clearSolr] could not be found in catalog [solr]
	at info.magnolia.commands.CommandsManager.executeCommand(CommandsManager.java:191)
	at nl.info.magnolia.solr.app.SolrManagementSubApp.clearSolrIndex(SolrManagementSubApp.java:110)
	at nl.info.magnolia.solr.app.SolrManagementAppViewImpl.lambda$createSolrIndexManagementSection$c34d7902$1(SolrManagementAppViewImpl.java:114)
	at nl.info.magnolia.solr.app.SolrManagementAppViewImpl$$Lambda$2/1642109817.buttonClick(Unknown Source)

**Comment by edgarvonk** [comment]
Hi, I will look into your second issue later. I am aware of the cleanSolr command. We ourselves created a second clearSolr command to actually remove all files from the Solr index. Maybe I forgot to include it in our module.

**Comment by edgarvonk** [comment]
Hi ropoman, your second reported issue related to the missing clearSolr command should be fixed (also in 2.0.0-SNAPSHOT). See: https://jira.magnolia-cms.com/browse/SOLRAPP-1

I have not been able to test the 2.0.0-SNAPSHOT version on Solr 5 yet.

PS: I keep track of issues and releases in Magnolia's JIRA not here on Github as this is part of the Magnolia Forge workflow. But no problem to report issues here.

**Comment by edgarvonk** [comment]
I managed to test it on Solr 5 now and all looks ok to me. I have released version 2.0.0 of my Solr App module that (only) works on Magnolia Solr modules version 5 and Solr 5.
